# Generated by Django 4.2.2 on 2023-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_qr', '0002_alter_reservation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkin_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
