# Generated by Django 4.2.2 on 2023-06-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_qr', '0004_remove_reservation_checkin_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkin_size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
