# Generated by Django 4.2.2 on 2023-06-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_qr', '0005_alter_checkin_checkin_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkin_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime checkin-ed'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime reserved'),
        ),
    ]
