# Generated by Django 4.2.2 on 2023-06-07 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_kana', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=200)),
                ('party_size', models.IntegerField(default=0)),
                ('reserved_at', models.DateTimeField(verbose_name='datetime reserved')),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_size', models.IntegerField(default=0)),
                ('checkin_at', models.DateTimeField(verbose_name='datetime checkin-ed')),
                ('notes', models.CharField(max_length=500)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_qr.reservation')),
            ],
        ),
    ]
