# Generated by Django 4.2.2 on 2023-06-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.CharField(default='', max_length=500),
        ),
    ]
